dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - pip install pip pytest pytest-pep8 pytest-doc pytest-cov tox coverage coveralls
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - pytest
after_success:
  - coveralls
