language: python
python:
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"
before_install:
  - pip install pytest pytest-pep8 pytest-doc pytest-cov coverage coveralls
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - pytest
  - tox
after_success:
  - coveralls