language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - pip install pytest pytest-pep8 pytest-doc pytest-cov coverage coveralls
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - pytest
after_success:
  - coveralls