language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - pip install --upgrade pip pytest pytest-pep8 pytest-doc pytest-cov tox coverage coveralls
install:
  - pip install --upgrade -r requirements.txt
  - python setup.py install
script:
  - pytest
after_success:
  - coveralls
